DROP TABLE IF EXISTS userinfo;

CREATE TABLE userinfo
(
	id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT(11) NULL DEFAULT NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	gender INT(11) NULL DEFAULT NULL ,
	createtime DATETIME NULL DEFAULT NULL, 
	PRIMARY KEY (id)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_USER START WITH 0 INCREMENT BY 1;