server:
  port: 8080
spring:
  application:
    name: springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123
    url: jdbc:mysql://localhost:3306/code-demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    #jdbc:mysql://localhost:3306/code-demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  # 用于性能监控
  jmx:
    enabled: true # 开启 jmx
  profiles:
    # 可以选择激活的配置例如： quartzdemo。默认是 default
    active: quartzdemo

#alibaba:
#  cloud:
#    access-key: '****'
#    secret-key: '****'

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
  server:
    port: 8081 # port=-1 则关闭 http
mybatis:
  config-location: classpath:mybatis-configuration.xml
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: top.clydezhou.lab.demo.springboot.dao

