alibaba:
  cloud:
    access-key: '****'
    secret-key: '****'
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
  server:
    port: 8081
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: top.clydezhou.lab.demo.springboot.dao
server:
  port: 8080
spring:
  application:
    name: springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: -pl,0OKM
    url: jdbc:mysql://localhost:3306/code-demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
