spring:
  datasource:
    url:
    password:
    username:

mybatis:
  type-handlers-package: top.clydezhou
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30