server:
    port: 8080
spring:
    profiles:
        active: h2
mybatis:
    #config-location: 'classpath:mybatis-configuration.xml'
    type-handlers-package: top.clydezhou.lab.demo.mybatis.spring.config.mybatis
    mapper-locations: 'classpath:mapper/*'