spring:
  datasource:
    url: jdbc:h2:./data/test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;INIT=RUNSCRIPT FROM 'classpath:database/sql/schema-h2.sql'\;
  h2:
    console:
      enabled: true
      path: /h2-console



