DROP TABLE IF EXISTS accountinfo;

CREATE TABLE IF NOT EXISTS `accountinfo` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(200) NOT NULL,
	`password` VARCHAR(200) NOT NULL,
	`nickname` VARCHAR(200),
	`createtime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`lastupdatetime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`flag` SMALLINT(6) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
);

truncate table accountinfo;

